import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="">
          <Link href="/kanto">관동지방</Link>
          <Link href="/johto">성도지방</Link>
          <Link href="/hoenn">호연지방</Link>
          <Link href="/sinnoh">신오지방</Link>
          <Link href="/unova">하나지방</Link>
          <Link href="/kalos">칼로스지방</Link>
          <Link href="/alola">알로라지방</Link>
          <Link href="/galar">가라르지방</Link>
          <Link href="/hisui">히스이지방</Link>
          <Link href="/paldea">팔데아지방</Link>
          <Link href="/">모든지방</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
